repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-o", "requirements.txt" ]
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
      - id: black
