version: 2.1
orbs:
  python: circleci/python@2.1.1
executors:
  python:
    docker:
      - image: cimg/python:3.11.0
jobs:
  install:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
  lint:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run isort . --check
      - run: poetry run black --check .
      - run: poetry run mypy -p src.bss_web_file_server
workflows:
  app:
    jobs:
      - install
      - lint
