version: 2.1
orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.5.0
  github-cli: circleci/github-cli@2.3.0
executors:
  python:
    docker:
      - image: cimg/python:3.12.2
defaults:
  docker_publish: &docker_publish
    image: bsstudio/bss-web-file-api
    registry: ghcr.io
    executor: docker/docker
    remote-docker-version: default
    use-remote-docker: true
    remote-docker-dlc: true
    use-buildkit: true
  tag_only: &tag_only
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /.*/
jobs:
  lint:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run isort . --check
      - run: poetry run black . --check
      - run: poetry run pylint src
      - run: poetry run mypy -p src
  verify-requirements:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry export -o requirements.txt
      - run: git diff --exit-code
  github_release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - github-cli/install:
          version: 2.43.1
      - github-cli/setup:
          version: 2.43.1
      - run: gh release create << pipeline.git.tag >> -t << pipeline.git.tag >> --generate-notes
  coverage:
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pytest --cov=src --cov-report=xml:./test-results/results/coverage.xml --cov-report=html:./test-results/coverage --cov-fail-under=100
      - store_test_results:
          path: test-results/results
      - store_artifacts:
          path: test-results/artifacts
workflows:
  Build:
    jobs:
      - lint:
          name: Lint
      - verify-requirements:
          name: Verify requirements.txt
      - python/test:
          name: Unit tests
          pkg-manager: poetry
          test-tool: pytest
          version: 3.12.2
      - docker/hadolint:
          name: Lint Dockerfile
      - docker/publish:
          name: Build docker image
          <<: *docker_publish
          deploy: false
  Release:
    jobs:
      - docker/publish:
          name: Publish image
          <<: [*docker_publish, *tag_only]
          tag: latest,<< pipeline.git.tag >>
      - github_release:
          name: Create release
          <<: *tag_only
