version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  lint:
    docker:
      - image: cimg/python:3.12.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run isort . --check
      - run: poetry run black . --check
      - run: poetry run mypy -p src.bss_web_file_server
workflows:
  Build:
    jobs:
      - lint
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
