version: 2.1
orbs:
  python: circleci/python@2.1.1
executors:
  python:
    docker:
      - image: cimg/python:3.11.0
jobs:
  install:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
workflows:
  app:
    jobs:
      - install
